---
apiVersion: v1
kind: Service
metadata:
  name: powerclicore-influxdb
  namespace: vmware
  labels:
    app: powerclicore
spec:
  ports:
    - port: 38083
      targetPort: 8083
      nodePort: 38083
      protocol: TCP
    - port: 38086
      targetPort: 8086
      nodePort: 38086
      protocol: TCP
  selector:
    app: powerclicore
    tier: influxdb
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerclicore-influxdb-pvc
  namespace: vmware
  labels:
    app: powerclicore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: powerclicore-influxdb
  namespace: vmware
  labels:
    app: powerclicore
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: powerclicore
        tier: influxdb
    spec:
      containers:
        - image: mycluster.icp:8500/vmware/influxdb:1.5.4-alpine
          name: influxdb
          env:
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: admin
            - name: INFLUXDB_DB
              value: powerclicore
            - name: INFLUXDB_USER
              value: powerclicore
            - name: INFLUXDB_USER_PASSWORD
              value: powerclicore
          ports:
            - containerPort: 8083
              name: influxdb-http
            - containerPort: 8086
              name: influxdb-api
          volumeMounts:
            - name: influxdb
              mountPath: /var/lib/influxdb/data
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: powerclicore-influxdb-pvc
