---
apiVersion: v1
kind: Service
metadata:
  name: vmware-influxdb
  namespace: vmware
  labels:
    app: vmware
spec:
  ports:
    # HTTP port
    - port: 38083
      targetPort: 8083
      nodePort: 38083
      protocol: TCP
    # REST API port
    - port: 38086
      targetPort: 8086
      nodePort: 38086
      protocol: TCP
  selector:
    app: vmware
    tier: influxdb
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmware-influxdb-pvc
  namespace: vmware
  labels:
    app: vmware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vmware-influxdb
  namespace: vmware
  labels:
    app: vmware
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vmware
        tier: influxdb
    spec:
      containers:
        - image: mycluster.icp:8500/vmware/influxdb:1.5.4-alpine
          name: influxdb
          env:
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: admin
            - name: INFLUXDB_DB
              value: vmware
            - name: INFLUXDB_USER
              value: vmware
            - name: INFLUXDB_USER_PASSWORD
              value: vmware
          ports:
            - containerPort: 8083
              name: influxdb-http
            - containerPort: 8086
              name: influxdb-api
          volumeMounts:
            - name: influxdb
              mountPath: /var/lib/influxdb/data
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: vmware-influxdb-pvc
