---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmware-influxdb-pv
  namespace: vmware
  labels:
    type: nfs
spec:
  capacity:
    storage:10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.71.9.51
    path: /vmware/vmware-influxdb-pv
  persistentVolumeReclaimPolicy: Recycle
