---
apiVersion: v1
kind: Service
metadata:
  name: vmware-powerclicore
  namespace: vmware
  labels:
    app: vmware
spec:
  ports:
    - port: 38083
      targetPort: 8083
      nodePort: 38083
      protocol: TCP
    - port: 38086
      targetPort: 8086
      nodePort: 38086
      protocol: TCP
  selector:
    app: vmware
    tier: influxdb
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmware-powerclicore-pvc
  namespace: vmware
  labels:
    app: vmware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vmware-powerclicore
  namespace: vmware
  labels:
    app: vmware
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vmware
        tier: powerclicore
    spec:
      containers:
        - image: mycluster.icp:8500/vmware/powerclicore:ubuntu16.04.0
          name: vmware-powerclicore

          ports:
            - containerPort: 8083
              name: influxdb-http
            - containerPort: 8086
              name: influxdb-api
          volumeMounts:
            - name: powerclicore
              mountPath: /var/lib/poweclicore/data
      volumes:
        - name: powerclicore
          persistentVolumeClaim:
            claimName: vmware-powerclicore-pvc
